### ISSUE TITLE
Port redshift-plasmoid to Plasma 5

### ISSUE THREAD

**Issue by mrueg** [simgunz/redshift-plasmoid#13]
Hi, 
I saw your post on kde-apps.org regarding Plasma 5. But unfortunately it looks like it will take some time until the dbus interface for redshift is ready.

So I'd like to know if the plans regarding plasma 5 have changed and a migration is possible?

Thanks!

**Comment by xdmx** [comment]
Hi @simgunz, plasma 5.2 will be released on Tuesday, do you have any update on supporting it? Your plasmoid is the most useful I use, I can't live without it :smile:

**Comment by simgunz** [comment]
Unfortunately I've been busy as hell in the past few months, so I cannot
respect the deadline I've previously set. But I'll try to work on it as
soon as I can. At least I've installed plasma 5 on a virtual machine, which
is the first step to begin the porting. I'll keep you updated.

**Comment by mrclayman** [comment]
Thanks, @simgunz. Redshift and its control plasmoid are two things on my desktop I can't live without.

Thanks a lot again for your effort. :)

**Comment by ochurlaud** [comment]
@simgunz did you have time to do the porting?

Else I can begin it if you want

**Comment by simgunz** [comment]
@ochurlaud I've done something. The dataengine has been ported and also the CMakeFiles (kind of). Now I need to port the applet (which means rewrite it in QML and make it communicate with the dataengine). If you want to start working on this it's fine. I'll try to push everything as soon as possible, so you can start from there.

Unfortunately I'm quite busy and I couldn't work on this. Moreover I had Plasma 5 on a virtual machine and was unstable and it was a pain working on it. I'll switch to Plasma 5 as soon as they release Plasma 5.3 on Manjaro, so then it'll be easy working on this.

**Comment by ochurlaud** [comment]
I worked a lot about this today... (see if you want my fork).. I first try to compile it like this without huge modifications. I have still a linking problem and the compilation didn't go to src/applet until now.

You will have troubles to get the latitudes/longitudes without fetching a webservice, because KSystemTimeZones (and all his friends) where removed from the KDE api...

**Comment by florianjacob** [comment]
> You will have troubles to get the latitudes/longitudes without fetching a webservice, because KSystemTimeZones (and all his friends) where removed from the KDE api...

Excuse me if I'm wrong, but Isn't it possible to use Plasma's Geolocation DataEngine? My plasma-workspace package on Arch Linux says optional dependencies are gpsd for GPS based geolocationand networkmanager-qt for IP based geolocation.

**Comment by ochurlaud** [comment]
I have no idea.. For now I'm  focusing on compiling: latitude = longitude = 0  by default :)

But I'll keep that it mind

**Comment by simgunz** [comment]
I still don't know how to replace KSystemTimeZones, I've just disabled it
as well. Time ago I had a look at the geolocation dataengine which seems
the obvious and most correct solution, but if I remember correctly that
dataengine was undocumented and not well supported (I haven't found any
application that was using it, it was developed for marble maybe). If you
don't have the GPS I would expect that that dataengine acquires the
position via GeoClue or using http://www.hostip.info/, but I was never able
to obtain my position in that way.

So if anyone have more information on that plasmoid works, we may figure
out how to use it properly.

Another solution is using the geoclue2 location provided by redshift itself
(added in the latest version). But also GeoClue is something not extremely
clear, and we should perform some test to see if redshift can actually get
the location.

**Comment by ochurlaud** [comment]
Have you already begun to design the QML?

I've never done this.. and I must say that it's absolutely not funny to do. Ok one should begin somewhere....

**Comment by ochurlaud** [comment]
Well I read the other applets developed by KDE people... The structure is totally different... 

I think we should rewrite it from scratch, and just reuse your code to do the job (meaning that it won't look like what you had). I'll create a new project on my account and will see what happens.

**Comment by simgunz** [comment]
I've pushed all the things I had done some weeks ago. The QML applet needs to be done from scratch. I've uploaded the basic package structure, the metadata file and a skeleton of the main.qml.

The dataengine seems to be working. For the applet you may need a support cpp file, because I don't know if the qml file is enough to do everything.

You may find info here:
http://notmart.org/

in particular plasma-sdk might be useful.

There were a nice series of tutorial on plasma 5 applet but I can't find them now.

**Comment by simgunz** [comment]
About the look of the applet, I'm pretty sure it's possible to obtain the same look using QML. Also the configuration ui files may be reusable.

**Comment by ochurlaud** [comment]
Apparently (I'm based on plasma-nm), you can reuse your ui without problem.

What needs to be in qml is only the interactive part (icon in the systray, right click/hoover on the icon). Then if you have for instance `right click > Configure`, you can just design the window behind `Configure` with a ui...

**Comment by simgunz** [comment]
Have you done any work on the redshift QML applet? Where can I find the code?

**Comment by ochurlaud** [comment]
@simgunz  not yet.. I'm pretty busy. And I'm trying first to *really* understand how it works... Therefore I read the networkmanager applet... I'll let you know this week

**Comment by simgunz** [comment]
Ok. Just to know, because I'm working on it now.

**Comment by ochurlaud** [comment]
are you on irc somewhere?

**Comment by simgunz** [comment]
My nick is simgunz and you can find me on #manjaro or #kde-devel

**Comment by stevenroose** [comment]
Any progress?

**Comment by ochurlaud** [comment]
@simgunz could you put somewhere the relevant screenshots? I reinstalled my computer lately and I don't have them anymore.... Thx

**Comment by ochurlaud** [comment]
What do you want in the context menu (when you click on the main icon):
- All the parameters (as in redshift.ui)
- A Config button
- a kitten
- something else

**Comment by stevenroose** [comment]
I'd expose as many functionality from the Redshift applet as possible. And a kitten is always nice to have. ([suggestion](https://s-media-cache-ak0.pinimg.com/236x/bb/48/3c/bb483c6ba90c8cb36bb4ebec758b8abf.jpg))

**Comment by ochurlaud** [comment]
In ~ 1h , i'll push what i've done on my fork. For now I'm only working on the design, since most of the function are going to be called from there in a js-like.

**Comment by ochurlaud** [comment]
The icon is not set, it's pretty ugly, but the basics are there: https://github.com/ochurlaud/redshift-plasmoid/tree/plasma5-porting/src/applet/package/contents/ui

**Comment by ochurlaud** [comment]
@simgunz: I would need to talk to you (irc for instance) to see how you want to manage the connection ui<-->backend. I can base it on what was there, but it seems too complex for what we want to achieve (ie: talk to Redshift?)

I want to be sure to understand everything.

Meanwhile, should I do a pull request?

**Comment by stevenroose** [comment]
@ochurlaud awesome that you are picking up the work here! :+1:

**Comment by ochurlaud** [comment]
@stevenroose btw, It's not a good idea to put this the configuration under the click. The previous behavior was: 
* on left-click: toogle the light
* on right-click: change parameters

Now, with what i've done, the toogle action cannot be performed....

**Comment by stevenroose** [comment]
In Ubuntu it was also right click > Toggle. That behavior is good enough

**Comment by simgunz** [comment]
Good to see that some job has been done. I'm currently on holiday and I'll
be back next Tuesday. I'll then review what has been done and I'll merge
it. If you want to work more on it, don't do the pull request now.
Thanks for the help.

**Comment by ochurlaud** [comment]
Ok.. I'm reading the code. I don't know where the RedshiftApplet::init() is called for instance, so I can't translate easily....

**Comment by ochurlaud** [comment]
https://techbase.kde.org/Development/Tutorials/Plasma2/QML2/API

**Comment by ochurlaud** [comment]
I did most of the design part. Still to bind the frontend to the dataengine.

On my fork the history is quite messy and the messages not well formatted, I'll change this before doing the pulling request

**Comment by Flutterfox** [comment]
Any news?

**Comment by ochurlaud** [comment]
here my pull request: 

 * https://github.com/simgunz/redshift-plasmoid/pull/16

I'll be in exam in middle of July, so I don't have any time to go further for more than a month. Help is highly welcomed!

**Comment by simgunz** [comment]
Hi,
unfortunately I have been busy all the weekends this month and I'll be away also this week end, so I physically didn't have time to look into the porting. I hope I can find some time next week, so that I can review the work Olivier has done and start from there.

@ochurlaud Again, thanks for your help.

**Comment by Flutterfox** [comment]
What all needs to be done? I am a developer, and would like to see if I can help.

**Comment by ochurlaud** [comment]
@Flutterfox see what I've done, read a lot of the links i gave above and try to do the link between redshift and the applet.

**Comment by Pastafarianist** [comment]
Has there been any progress in the last weeks?

**Comment by ochurlaud** [comment]
As you can see, my pull request hasn't been merge, I haven't done another one, and no one have pushed any code.  So nothing happened. I don't have time to work further for the moment. And since it's the first time I use the KF5/Plasma libs, it's a huge time investment for me...

**Comment by Flutterfox** [comment]
The time investment in learning KF5/Plasma is exactly why I haven't contributed as I initially planned to. Work has picked up since I posted, and I haven't had the opportunity to donate that much time.

**Comment by simgunz** [comment]
I'm working on the porting today. One of the reason why the porting is taking so much time is that the information for developing/porting Plasmoid on Plasma5 are sparse/hard to find/obsolete. There are tutorial for building Hello World plasmoid but when something more complex needs to be done it's hard to find information and often the only way is to reverse engineering others code.

I think this is supposed to be the API reference page for QML2, but it's not complete.
https://techbase.kde.org/Development/Tutorials/Plasma2/QML2/API#Service

@ochurlaud 
Can you post here some reference for:
- how to use tooltips
- how to use the config system

Regarding the config system, I need to find out how to set default values.

For debugging the plasmoid I've tried console.log('message') but when I run the plasmoid with plasmoidviewer or plasmawindowed I don't see any message on the console.
Is it the corret way to print debugging messages?

**Comment by ochurlaud** [comment]
For the tooltips, see  http://api.kde.org/frameworks-api/frameworks5-apidocs/plasma-framework/html/classToolTip.html

For the config system I don't know what you are referring to, but I used mostly the clock applet (link above)

To debug, I was creating some popups, but it's really really hard to deal with... Have fun =)

**Comment by simgunz** [comment]
Thanks.

The way you manage the tooltip is this:

Plasmoid.toolTipMainText = 'text'

which is not documented in that page.

**Comment by ochurlaud** [comment]
It may have evolve again :)

**Comment by ochurlaud** [comment]
Oh! sorry this something else...
It's directly in the plasmoid class. Wait I'm looking for this

**Comment by simgunz** [comment]
Another useful reference:
https://community.kde.org/Plasma/PortingQMLPlasmoids

**Comment by ochurlaud** [comment]
http://api.kde.org/frameworks-api/frameworks5-apidocs/plasma-framework/html/classAppletInterface.html

**Comment by ochurlaud** [comment]
Yes I used your reference a lot...

**Comment by ochurlaud** [comment]
We should list all those reference and put them somewhere relevant on techbase.kde.org

**Comment by ochurlaud** [comment]
Could you try to push your code every time you go a step further so that we could give you a hand and see the progress?

**Comment by simgunz** [comment]
Yes. I didn't produce any code actually. I've just reviewed your code and
try to understand something about Plasma 5 and how to use all the
libraries. Let's see if I can make some step ahead next weekend.

**Comment by simgunz** [comment]
Unfortunately I still didn't work much on the porting and now I'll be busy for a full month. I hope to find some spare time to work on this.

**Comment by simgunz** [comment]
Apparently someone create a new plasmoid in qml 2 for redshift. Apparently it's full qml, so it doesn't require to be compiled nor a dataengine. I didn't tried it yet.

http://kde-apps.org/content/show.php/Redshift+Control?content=170746

**Comment by ochurlaud** [comment]
it works well... Some features are missing but not much...

**Comment by ochurlaud** [comment]
Sorry but i think it is it :)

**Comment by simgunz** [comment]
Good. I hope to see activity support back. I may help in bringing the missing feature back if I eventually find the time to learn how to do it.
