### ISSUE TITLE
Redshift fails to start on Debian jessie

### ISSUE THREAD

**Issue by mryellow** [simgunz/redshift-plasmoid#26]
Having read this comment where you explain the startup, seems this must have fallen into a hole: 
 https://github.com/simgunz/redshift-plasmoid/issues/1#issuecomment-6123727

The applet runs, however nothing happens when clicked and no process shows under `ps aux | grep redshift`. Re-saving the configuration doesn't seem to launch `redshift`, assuming that should happen.

Believe it may be related to a kernel update. Started happening just now after rebooting, have been running it fine previously.

`uname -rv`
`3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)`

If I run `redshift -O 3000` directly the colour updates as expected.

**Comment by mryellow** [comment]
Running `redshiftautostart` manually kicks it into life.

**Comment by simgunz** [comment]
Did ou solve this issue?

redshiftautostart needs to run for the applet to work. The script should autostart when the system boot.

**Comment by mryellow** [comment]
Yeah was still an issue, however moved on to Debian Stretch recently. All seems to work fine after reinstalling a few things during the upgrade.

**Comment by simgunz** [comment]
Good.
