### ISSUE TITLE
option to set default mode (brightness or temp)

### ISSUE THREAD

**Issue by atomGit** [simgunz/redshift-plasmoid#28]
would be nice to have an option to set the default mode when redshift is loaded - currently it starts in temp mode and i'd like it to start in brightness mode and avoid the middle click to change it

**Comment by simgunz** [comment]
I think you are referring to plasma-redshift-control which is a different widget. Open a bug here:

https://bugs.kde.org/buglist.cgi?component=General&product=plasma-redshift-control&resolution=---
